### PR TITLE
bumps node & distro for travis ci

### PR DESCRIPTION
**Pull request by Jesssullivan**
Travis tests failing on node 4 & 6, bumps those to 10 & 12.  
- [Tests](https://travis-ci.org/github/Jesssullivan/fft.js/builds/754570001)    ([Build Status](http://travis-ci.org/jesssullivan/fft.js))

### CODE REVIEW

**Comment by Jesssullivan** [comment]
Thought I'd check back on this ;)

**Comment by Jesssullivan** [comment]
Thought I'd check back on this ;)

**Review by indutny — CHANGES_REQUESTED** [review]
Hey! Thanks for this PR.

I'm a bit confused why you used JSON in the yml file. The changes looks good to me, but I wish to keep the yaml format (given that the file's extension didn't change).

**Comment by Jesssullivan** [comment]
Yikes!  Thanks.

**Comment by Jesssullivan** [comment]
changed-
It appears travis-ci.org is shutting down in [favor of travis-ci.com](https://travis-ci.community/t/extremely-poor-official-communication-of-the-org-shutdown/10568/4) :grimacing: - here is this pr [on the latter](https://travis-ci.com/github/Jesssullivan/fft.js/builds/215238744/config)

**Review by indutny — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
